### ISSUE TITLE
Online decoding?

### ISSUE THREAD

**Issue by GatechLW** [api-ai/asr-server#14]
Thanks for sharing this awesome project. I have run it and test by using my own voice. the ASR accuracy is good. Some questions about this project,

1. It seems that this project don't support online decoding, namely only when user press stop button, then the decoder on the server started to decoding the received raw data. Am I right?

2. I find that in the kaldi model folder, the model file is stored in final.mdl, not final.nnet, so I am wondering whether current project is decoding using GMM-HMM model, not nnet model?

Thanks in advance!

**Comment by realill** [comment]
It does support online decoding but you have to send data as multipart. I believe our html client support this. See intermediate and multipart parameters https://github.com/api-ai/asr-server

api.ai model was trained using kaldi nnet3 chain models http://kaldi-asr.org/doc/chain.html. This is neural network models, it still use hmm, tho (all of them do as far as I know). asr-server was built to work with any almost any nnet3 models.

**Comment by viju2008** [comment]
Can you please provide us the https://api.ai/downloads/api.ai-kaldi-asr-model.zip

We are unable to download its giving 404 error

**Comment by YunzhaoLu** [comment]
I changed the following code in main.js
       var URL = "/asr?multipart=true"
the result only output after stopping mic button. 
I installed "httpd" with CentOS. Is there any advice how to run online decoding? I would expect 2 partial results and one final result if I talk 10 seconds, but there is only one final result.

thanks,
Luke

**Comment by realill** [comment]
It looks like I was wrong and asr-html does not support multipart and partial results. You have to use curl to test it out. I do not have example for it.

We used to have multipart html example but it looks like it lost now.

**Comment by YunzhaoLu** [comment]
I tried two commands as following, but no partial results returned.

[usnmp@zotac-01 temp]$ curl -H "Content-Type: application/octet-stream" --data-binary @2075_S_1464731780214.wav http://localhost/asr?multipart=true

--ResponseBoundary
Content-Disposition: form-data; name="result"
Content-type: application/json

{"status":"ok","data":[{"confidence":0.955022,"text":"北 京 建 议 还 跟 这 个 台 灯 笼 祭 坛 今 晚 到 达 的 地 价 不 出 去 见 杨 幂 量 多 好 啊 您 您 在 什 么 啊 真 的 有 美 貌 的 折 价 一 个 长 得 又 帅 的 又 有 钱 的 哦 一 个 就 不 用 出 来 混 了 哦 维 金 娜 不 知 道 没 看 到 给 好 友 慨 啊 啊 哦 你 离 开 为 好 强 啊 爱 你 还 起 骂 我 觉 得 他 安 然 长 了 有 对 象 小 白 脸 型 的 啊 嗯 这 一 名 隐 士 巅 听 多 了 哈 娜 姐 呀 好 男 人 都 得 跳 水 里 来 面 对 啊 了 就 让 他 们 这 样 您 就 好 了 也 许 就 蛰 表 面 上 了 你 也 许 吧 唉 这 这 也 述 说 不 定 啊 外 那 个 们 就 他 们 的 山 着 那 个 叫 谁 的 啊 摇 的 那 么 的 乐 趣 当 面 跟 马 伊 俐 啊 就 是 人 那 样 嗯 嗯 嗯 诚 恳 地 道 个 歉 什 么 受 得 马 伊 俐 的 原 谅 他 们 两 个 人 了 那 叫 心 里 觉 平 衡 风 景 的 不 计 较 了 哦 络 文 章 什 么 态 度 呀 爬 呀 那 不 是 又 有 真 情 的 两 个 人 被 活 活 拆 散 了 吗 而 禁 不 住 诱 惑 了 就 就 会 很 觉 特 好 吗 那 也 不 是 有 的 的 问 题 啊 生 那 您 就 什 么 样 的 人 他 外 面 就 没 有 妈 喔 喔"}]}

--ResponseBoundary--
[usnmp@zotac-01 temp]$ curl -H "Content-Type: multipart/form-data" --data-binary @2075_S_1464731780214.wav http://localhost/asr?multipart=true

--ResponseBoundary
Content-Disposition: form-data; name="result"
Content-type: application/json

{"status":"ok","data":[{"confidence":0.955024,"text":"北 京 建 议 还 跟 这 个 台 灯 笼 祭 坛 今 晚 到 达 的 地 价 不 出 去 见 杨 幂 量 多 好 啊 您 您 在 什 么 啊 真 的 有 美 貌 的 折 价 一 个 长 得 又 帅 的 又 有 钱 的 哦 一 个 就 不 用 出 来 混 了 哦 维 金 娜 不 知 道 没 看 到 给 好 友 慨 啊 啊 哦 你 离 开 为 好 强 啊 爱 你 还 起 骂 我 觉 得 他 安 然 长 了 有 对 象 小 白 脸 行 了 啊 嗯 这 一 名 隐 士 巅 听 多 了 哈 娜 姐 呀 好 男 人 都 得 跳 水 里 来 面 对 啊 我 就 让 他 们 这 样 您 就 好 了 也 许 就 蛰 表 面 上 了 你 也 许 吧 唉 这 这 也 述 说 不 定 啊 外 那 个 们 就 他 们 的 山 着 那 个 叫 谁 的 啊 摇 的 那 么 的 乐 趣 当 面 跟 马 伊 俐 啊 就 是 人 那 样 嗯 嗯 嗯 诚 恳 地 道 个 歉 什 么 受 得 马 伊 俐 的 原 谅 他 们 两 个 人 了 那 叫 心 里 觉 平 衡 风 景 的 不 计 较 了 哦 络 文 章 什 么 态 度 呀 爬 呀 那 不 是 又 有 真 情 的 两 个 人 被 活 活 拆 散 了 吗 而 禁 不 住 诱 惑 了 就 就 会 很 觉 特 好 吗 那 也 不 是 有 的 的 问 题 啊 生 那 您 就 什 么 样 的 人 他 外 面 就 没 有 妈 喔 喔"}]}

--ResponseBoundary--

**Comment by YunzhaoLu** [comment]
Thank you again!
