### ISSUE TITLE
Recognition model not available to download anymore?

### ISSUE THREAD

**Issue by jbuck** [api-ai/asr-server#18]
Edit - Bah, hit enter too soon

Hi, I'm attempting to follow the installation instructions given in the README. When I try to download the recognition model I get a 404: https://api.ai/downloads/api.ai-kaldi-asr-model.zip

Is there another location to download this model or is it not available anymore?

Thanks, Jon

**Comment by viju2008** [comment]
Did you get the model 
Viju

**Comment by andrenatal** [comment]
@jbuck new model is here: http://static.api.ai/downloads/api.ai-kaldi-asr-model.zip

**Comment by realill** [comment]
New official location is https://github.com/api-ai/api-ai-english-asr-model/releases/download/1.0/api.ai-kaldi-asr-model.zip
