### ISSUE TITLE
Unable to download API AI ASR MODEL https://api.ai/downloads/api.ai-kaldi-asr-model.zip

### ISSUE THREAD

**Issue by viju2008** [api-ai/asr-server#20]
Unable to download API AI ASR MODEL https://api.ai/downloads/api.ai-kaldi-asr-model.zip

Is the model available for download now or not available

**Comment by realill** [comment]
We should rehost this model somewhere on kaldi servers

**Comment by realill** [comment]
New link http://static.api.ai/downloads/api.ai-kaldi-asr-model.zip
