### ISSUE TITLE
Low throughput w/ kaldi + asr-server + kaldi

### ISSUE THREAD

**Issue by milescrabill** [api-ai/asr-server#24]
I am testing using nginx -> fastcgi_pass -> asr-server -> kaldi successfully, but the throughput we're getting is very low - on the order of 1-2rq/ps using significantly sized AWS instances.

Do people have similar experiences using this in production? We're running running with the `../asr-server/fcgi-nnet3-decoder --fcgi-socket=:8000` option.

**Comment by milescrabill** [comment]
We've gotten better throughput since this issue was created (mostly by adjusting thread count and sizing up to instances with more cores). For those that don't know, you can pass `fcgi-nnet3-decoder` a flag `--fcgi-threads-number=${processorcount}` where ${processorcount} is an integer.

**Comment by ananda621** [comment]
@milescrabill wondering what throughput you were able to achieve and the kind of AWS instance being used - it'd really help for a rough cost estimate, thank you for your time!

**Comment by milescrabill** [comment]
@ananda621 We're overspecced for our workloads, but we're using c4.4xlarges.
