### ISSUE TITLE
Errors buiding asr-server with kaldi release as of May 10, 2016 (CentOS 6.7, g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)

### ISSUE THREAD

**Issue by zalextth** [api-ai/asr-server#3]
g++ -msse -msse2 -Wall -I.. -pthread -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -rdynamic -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/xyz/apiai/kaldi-apiai/tools/ATLAS/include -I/home/xyz/apiai/kaldi-apiai/tools/openfst/include -I/home/xyz/apiai/kaldi-apiai/src -L/home/xyz/apiai/kaldi-apiai/src  -g    -c -o Nnet3LatgenFasterDecoder.o Nnet3LatgenFasterDecoder.cc
In file included from Nnet3LatgenFasterDecoder.cc:16:
Nnet3LatgenFasterDecoder.h:49: error: 'OnlineNnet2FeaturePipelineConfig' in namespace 'kaldi' does not name a type
Nnet3LatgenFasterDecoder.h:52: error: ISO C++ forbids declaration of 'OnlineNnet2FeaturePipelineInfo' with no type
Nnet3LatgenFasterDecoder.h:52: error: invalid use of '::'
Nnet3LatgenFasterDecoder.h:52: error: expected ';' before '*' token
Nnet3LatgenFasterDecoder.h:58: error: ISO C++ forbids declaration of 'OnlineIvectorExtractorAdaptationState' with no type
Nnet3LatgenFasterDecoder.h:58: error: invalid use of '::'
Nnet3LatgenFasterDecoder.h:58: error: expected ';' before '*' token
Nnet3LatgenFasterDecoder.h:59: error: ISO C++ forbids declaration of 'OnlineNnet2FeaturePipeline' with no type
Nnet3LatgenFasterDecoder.h:59: error: invalid use of '::'
Nnet3LatgenFasterDecoder.h:59: error: expected ';' before '*' token
Nnet3LatgenFasterDecoder.cc: In constructor 'apiai::Nnet3LatgenFasterDecoder::Nnet3LatgenFasterDecoder()':
Nnet3LatgenFasterDecoder.cc:25: error: 'feature_info_' was not declared in this scope
Nnet3LatgenFasterDecoder.cc: In destructor 'virtual apiai::Nnet3LatgenFasterDecoder::~Nnet3LatgenFasterDecoder()':
Nnet3LatgenFasterDecoder.cc:33: error: 'feature_info_' was not declared in this scope
Nnet3LatgenFasterDecoder.cc: In member function 'virtual void apiai::Nnet3LatgenFasterDecoder::RegisterOptions(kaldi::OptionsItf&)':
Nnet3LatgenFasterDecoder.cc:55: error: 'feature_config_' was not declared in this scope
Nnet3LatgenFasterDecoder.cc: In member function 'virtual bool apiai::Nnet3LatgenFasterDecoder::Initialize(kaldi::OptionsItf&)':
Nnet3LatgenFasterDecoder.cc:73: error: 'feature_info_' was not declared in this scope
Nnet3LatgenFasterDecoder.cc:73: error: expected type-specifier
Nnet3LatgenFasterDecoder.cc:73: error: expected ';'
Nnet3LatgenFasterDecoder.cc: In member function 'virtual void apiai::Nnet3LatgenFasterDecoder::InputStarted()':
Nnet3LatgenFasterDecoder.cc:105: error: 'adaptation_state_' was not declared in this scope
Nnet3LatgenFasterDecoder.cc:105: error: expected type-specifier
Nnet3LatgenFasterDecoder.cc:105: error: expected ';'
Nnet3LatgenFasterDecoder.cc:107: error: 'feature_pipeline_' was not declared in this scope
Nnet3LatgenFasterDecoder.cc:107: error: expected type-specifier
Nnet3LatgenFasterDecoder.cc:107: error: expected ';'
Nnet3LatgenFasterDecoder.cc: In member function 'virtual void apiai::Nnet3LatgenFasterDecoder::CleanUp()':
Nnet3LatgenFasterDecoder.cc:121: error: 'adaptation_state_' was not declared in this scope
Nnet3LatgenFasterDecoder.cc:122: error: 'feature_pipeline_' was not declared in this scope
Nnet3LatgenFasterDecoder.cc: In member function 'virtual bool apiai::Nnet3LatgenFasterDecoder::AcceptWaveform(kaldi::BaseFloat, const kaldi::VectorBase<float>&)':
Nnet3LatgenFasterDecoder.cc:132: error: 'feature_pipeline_' was not declared in this scope
Nnet3LatgenFasterDecoder.cc: In member function 'virtual void apiai::Nnet3LatgenFasterDecoder::InputFinished()':
Nnet3LatgenFasterDecoder.cc:144: error: 'feature_pipeline_' was not declared in this scope
Nnet3LatgenFasterDecoder.cc: In member function 'virtual void apiai::Nnet3LatgenFasterDecoder::GetLattice(kaldi::CompactLattice*)':
Nnet3LatgenFasterDecoder.cc:156: error: 'feature_pipeline_' was not declared in this scope
Nnet3LatgenFasterDecoder.cc:156: error: 'adaptation_state_' was not declared in this scope
/home/xyz/apiai/kaldi-apiai/src/base/kaldi-math.h: At global scope:
/home/xyz/apiai/kaldi-apiai/src/base/kaldi-math.h:130: warning: 'kaldi::kLogZeroBaseFloat' defined but not used
cc1plus: warning: unrecognized command line option "-Wno-unused-local-typedefs"
make[1]: *** [Nnet3LatgenFasterDecoder.o] Error 1
make[1]: Leaving directory `/home/xyz/apiai/asr-server/src'
make: *** [all] Error 2

**Comment by realill** [comment]
@zalextth were you able to compile kaldi itself?

**Comment by zalextth** [comment]
Kaldi has been built without issues.

**Comment by realill** [comment]
@folomeev  please look into this.

**Comment by folomeev** [comment]
Fixed. 
@zalextth You may pull changes and re-run make. Everything should be fine.

**Comment by zalextth** [comment]
Confirmed. Thank you.
