### ISSUE TITLE
Mac OS Compatibility: pthread_tryjoin_np

### ISSUE THREAD

**Issue by maxhawkins** [api-ai/asr-server#4]
Thanks for open sourcing this library. It looks like great code and I'm eager to try it out!

I tried compiling on Mac but ran into some issues. There were some minor problems with the configure script and one compilation error. Unfortunately `pthread_threadid_np` is not supported on Mac OS.

```
FcgiDecodingApp.cc:233:10: error: use of undeclared identifier
      'pthread_tryjoin_np'; did you mean 'pthread_threadid_np'?
                                if (!pthread_tryjoin_np(*i, NULL)) {
                                     ^~~~~~~~~~~~~~~~~~
                                     pthread_threadid_np
```

**Comment by folomeev** [comment]
Hello! Thank you for your interest in our code. 

Frankly speaking, we did not expect that the code will be used on platforms other than Linux, so for this reason not portable function has been used.
Since there is a need to make a build for MacOS, I will try to prepare a fix in the coming days.

Thank you!

**Comment by realill** [comment]
@maxhawkins if you going to fix it yourself, feel free to send us pull request for this

**Comment by maxhawkins** [comment]
Thank you. I ended up installing the code in a Docker container and side-stepping the issue. I know a lot of people develop on a Mac which is why I opened the issue.

Let me take a stab at a pull request today. I'm a newbie to pthreads so I wanted to let you know about the compilation problem before I dug into a fix.
