### ISSUE TITLE
help fix 404 not found

### ISSUE THREAD

**Issue by maxcogay** [api-ai/asr-server#40]
![image](https://user-images.githubusercontent.com/41080757/43688663-228f57f2-9917-11e8-8d12-06d28a28b30f.png)

**Comment by hc038** [comment]
hey @maxcogay did you solve this issue?

**Comment by realill** [comment]
This means apache was not setup correctly and /asr target is unavalable.

**Comment by realill** [comment]
Double check your configs according to https://github.com/dialogflow/asr-server#configuring-apache2, especially part about ProxyPass. See apache logs for errors and warnings on initialization.
