### ISSUE TITLE
curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by saber5433** [api-ai/asr-server#41]
How could I fix it？
![95a1c252361cd708a5895657b9e2473](https://user-images.githubusercontent.com/15922669/44974826-5ff8e300-af93-11e8-8bf9-11eab63a4b3c.png)

**Comment by saber5433** [comment]
@realill

**Comment by saber5433** [comment]
@realill

**Comment by realill** [comment]
You need to look into server log to understand the error
