### ISSUE TITLE
ERROR (fcgi-nnet3-decoder[5.4]:DecodableNnetLoopedOnlineBase():decodable-online-looped.cc:45) Input feature dimension mismatch: got 40 but network expects 43

### ISSUE THREAD

**Issue by saber5433** [api-ai/asr-server#42]
How could I fix it? I am trying to decode the chain model of AISELL-2.
![f12d17792c2507061b94bb942280e8f](https://user-images.githubusercontent.com/15922669/45021930-7d967d00-b065-11e8-97a3-e61f00eb7768.png)

**Comment by saber5433** [comment]
@realill

**Comment by 00001101-xt** [comment]
Add these two options `--add-pitch=true --online-pitch-config=pitch.conf` may help.

**Comment by saber5433** [comment]
> 添加这两个选项`--add-pitch=true --online-pitch-config=pitch.conf`可能会有所帮助。

Thanks !

**Comment by saber5433** [comment]
> Add these two options `--add-pitch=true --online-pitch-config=pitch.conf` may help.

Thanks !
