### ISSUE TITLE
Real-time factor

### ISSUE THREAD

**Issue by LqNoob** [api-ai/asr-server#45]
If considering real-time factor，How did you improve the recognition speed of "Decode"?

**Comment by realill** [comment]
If you are asking about what effect does real-time have. It is crucial to have for any interactive ASR system, You do not want user who made 10 seconds speech to wait 9 seconds for ASR system to process. You want results almost immediately as user stopped speaking.

**Comment by LqNoob** [comment]
Thank you for your reply.
 But what I want to ask is "How did you get the results immediately as user stopped speaking？".  
 How to improve the speed of recognition？
