### ISSUE TITLE
how to use a big LM to rescore the small LM result?

### ISSUE THREAD

**Issue by xinq2016** [api-ai/asr-server#6]
How can I join the rescore to the api-ai server?  Or how can I change the decode mode to LatticeBiglmFastDecoder?

Many thanks

**Comment by realill** [comment]
Server is using Nnet3LatgenFasterDecoder right now. I guess you can rewrite it to use any other compatible kaldi decoder. But you will have to do your own coding for this.

https://github.com/api-ai/asr-server/blob/master/src/Nnet3LatgenFasterDecoder.cc
