### ISSUE TITLE
Rebuild when server running

### ISSUE THREAD

**Issue by xinq2016** [api-ai/asr-server#8]
When I use the FastCGI api-ai server, the repository often been rebuilded.
LOG (fcgi-nnet3-decoder:RebuildRepository():determinize-lattice-pruned.cc:283) Rebuilding repository.

How can I fix it?

Many thanks

**Comment by folomeev** [comment]
Hello!

I took a look to RebuildRespository() method comments:

// rebuild the string repository,    
// freeing stuff we don't need.. we call this when memory usage
// passes a supplied threshold.  We need to accumulate all the
// strings we need the repository to "remember", then tell it
// to clean the repository.

and as I saw in code, this method is called when memory usage exceeds some threshold defined by "max-mem" option. 

I guess that that you pass "--max-mem" option with some non-default value and it causes repository rebuild. Try to increase the passed value or do not pass it at all.
